create table persons (
  id bigint generated by default as identity primary key,
  personal_no varchar(50) not null,
  rank varchar(50),
  full_name varchar(200) not null,
  sex char(1) not null,
  birth_date date not null,
  "position" varchar(200),
  "group" varchar(100),
  direction varchar(100),
  department_unit varchar(200),
  department varchar(200),
  service varchar(200),
  is_command_reserve smallint default 0 not null,
  position_assigned_date date,
  combat_start_date date,
  combat_end_date date,
  combat_region varchar(200),
  reserve_position varchar(200),
  dactyl_card_reg_no varchar(50),
  employee_category varchar(100),
  active_reserve_1 varchar(50),
  special_attestation_present smallint default 0 not null,
  agent_admission_order_date date,
  health_group varchar(50),
  physical_group varchar(50),
  dispensary_date date,
  gb_service_period_start date,
  snils varchar(20),
  service_id_1 varchar(50),
  service_id_2 varchar(50),
  inn varchar(20),
  dismiss_reason varchar(200),
  dismiss_date date,
  contract_end_date date,
  status varchar(30) not null,
  status_changed_at timestamp,
  last_import_id bigint,
  created_at timestamp default current_timestamp,
  created_by varchar(100) not null,
  updated_at timestamp,
  updated_by varchar(100),
  is_deleted smallint default 0 not null,
  constraint ck_persons_sex check (sex in ('M','F')),
  constraint ck_persons_status check (status in ('active','inactive_commandered','inactive_dismissed','inactive_other')),
  constraint ck_persons_is_deleted check (is_deleted in (0,1))
);

create unique index ux_persons_personal_no on persons(personal_no);
create index ix_persons_full_name on persons(full_name);
create index ix_persons_status on persons(status);

create table test_sessions (
  id bigint generated by default as identity primary key,
  session_date date not null,
  norms_id varchar(50) not null,
  norms_pack_hash varchar(64) not null,
  policies_snapshot_json blob sub_type text not null,
  rules_version varchar(20) not null,
  status varchar(20) not null,
  created_by varchar(100) not null,
  created_at timestamp default current_timestamp,
  updated_at timestamp,
  updated_by varchar(100)
);

create index ix_test_sessions_date on test_sessions(session_date);

create table session_participants (
  id bigint generated by default as identity primary key,
  session_id bigint not null references test_sessions(id),
  person_id bigint not null references persons(id),
  participation_status varchar(30) not null,
  participation_reason_code varchar(40),
  participation_reason_text varchar(200),
  status_reason varchar(200),
  sex_snapshot char(1) not null,
  birth_date_snapshot date not null,
  age_group_base smallint not null,
  age_group_med_delta smallint default 0 not null,
  age_group_effective smallint not null,
  age_group_med_reason varchar(200),
  age_group_med_source varchar(30),
  category_fp_assigned smallint not null,
  category_fp_source varchar(20) not null,
  category_default_reason varchar(200),
  constraint ck_sess_part_category check (category_fp_assigned in (1,2,3)),
  constraint ck_sess_part_src check (category_fp_source in ('auto_default','manual_override','policy_force_3')),
  constraint ck_sess_part_age_src check (age_group_med_source is null or age_group_med_source in ('manual','medical_commission')),
  constraint ck_sess_part_sex_snap check (sex_snapshot in ('M','F')),
  constraint ck_session_participants_status check (participation_status in ('completed','refuse','no_show_invalid','no_show_valid','medical_exempt','lfk')),
  constraint ck_session_participants_reason check (participation_reason_code is null or participation_reason_code in ('BUSINESS_TRIP','DUTY','VACATION','SICK_LEAVE','MEDICAL_EXEMPT','LFK','NO_SHOW'))
);

create unique index ux_session_participants on session_participants(session_id, person_id);

create table session_assignments (
  id bigint generated by default as identity primary key,
  session_participant_id bigint not null references session_participants(id),
  n_required smallint not null,
  assignment_mode varchar(20) not null,
  assignment_reason varchar(200),
  constraint ck_session_assignments_mode check (assignment_mode in ('auto_suggest','manual'))
);

create unique index ux_session_assignments on session_assignments(session_participant_id);

create table assignment_exercises (
  id bigint generated by default as identity primary key,
  session_assignment_id bigint not null references session_assignments(id),
  exercise_id integer not null,
  variant_id varchar(50),
  quality_group varchar(20) not null,
  sort_order smallint,
  is_counted smallint default 1,
  constraint ck_assign_ex_is_counted check (is_counted in (0,1))
);

create table attempt_results (
  id bigint generated by default as identity primary key,
  assignment_exercise_id bigint not null references assignment_exercises(id),
  attempt_no smallint not null,
  status varchar(30) not null,
  status_reason varchar(200),
  raw_result_str varchar(50),
  normalized_value double precision,
  normalized_unit varchar(10),
  points smallint,
  norm_row_id varchar(50),
  out_of_scale smallint default 0 not null,
  out_of_scale_policy varchar(20),
  constraint ck_attempt_results_status check (status in ('entered','completed','not_counted','invalid')),
  constraint ck_attempt_results_out_of_scale check (out_of_scale in (0,1))
);

create unique index ux_attempt_results on attempt_results(assignment_exercise_id, attempt_no);

create table calculated_results (
  id bigint generated by default as identity primary key,
  session_participant_id bigint not null references session_participants(id),
  total_points smallint,
  final_grade varchar(20),
  final_reason_code varchar(40) not null,
  qualification_level varchar(20),
  qualification_reason_code varchar(40),
  calculation_ts timestamp default current_timestamp,
  thresholds_snapshot_json blob sub_type text
);

create unique index ux_calculated_results on calculated_results(session_participant_id);

create table import_batches (
  id bigint generated by default as identity primary key,
  created_at timestamp default current_timestamp,
  source_filename varchar(200),
  source_type varchar(10),
  report_json blob sub_type text
);

create table mapping_presets (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  mapping_json blob sub_type text not null
);

create table audit_log (
  id bigint generated by default as identity primary key,
  ts timestamp default current_timestamp,
  user_name varchar(100) not null,
  entity_type varchar(30) not null,
  entity_id bigint,
  action varchar(30) not null,
  data_json blob sub_type text
);

create index ix_audit_log_ts on audit_log(ts);
create index ix_audit_log_entity on audit_log(entity_type, entity_id);

create table locks (
  id bigint generated by default as identity primary key,
  entity_type varchar(30) not null,
  entity_id bigint not null,
  locked_by varchar(100) not null,
  locked_at timestamp default current_timestamp not null,
  expires_at timestamp,
  reason varchar(200)
);

create unique index ux_locks on locks(entity_type, entity_id);

alter table test_sessions
  add constraint ck_test_sessions_status check (status in ('draft','active','locked','archived'));
